### ISSUE TITLE
/filepointer.json (Permission denied) issue

### ISSUE THREAD

**Issue by shahidmgr** [Appdynamics/log-monitoring-extension#11]
[Monitor-Task-Thread1] 04 Aug 2020 07:02:54,046 ERROR FilePointerProcessor-Log Monitor - Unfortunately an error occurred while saving filepointers to /filepointer.json
java.io.FileNotFoundException: /filepointer.json (Permission denied)
[Monitor-Task-Thread7] 04 Aug 2020 07:02:54,075 ERROR FilePointerProcessor-Log Monitor - Unfortunately an error occurred while saving filepointers to /filepointer.json
java.io.FileNotFoundException: /filepointer.json (Permission denied)

**Comment by shahidmgr** [comment]
Hi Team,

If anyone comes across this issue please help me to fix this.

Thanks in advance.
Shahid

**Comment by 3ll34ndr0** [comment]
Hi, 
same problem here with version logmonitor-4.0.1.

**Comment by garychappell** [comment]
Same problem here... even tried the latest 4.0.2 version.
